-- AlterTable
ALTER TABLE `PdfTextLine` MODIFY `attribute` ENUM('KNOWLEDGEABLE', 'ENGAGING', 'SUPPORTIVE', 'CLEAR', 'PASSIONATE', 'CONFUSING', 'UNFAIR', 'BORING', 'UNHELPFUL', 'DISORGANIZED', 'OTHER') NULL;
